spring:
  application:
    name: sample-springdata-service
  datasource:
    url: jdbc:mysql://localhost/eaproject
    username: eaproject1
    password: test1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: service-user
      password: 3b99fef5-8b7d-4984-a3d6-124c26914ed7
  mail:
    host: smtp.gmail.com
    port: 587
    username: eaairlinereservation@gmail.com
    password: cs544project
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  smtp:
    debug: true
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
  level:
    org:
      springframework:
        web=DEBUG:
spring-boot-server.name: EMAILSERVER
email.from: eaairlinereservation@gmail.com
